# Generated by Django 5.1.4 on 2026-02-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
