# Generated by Django 5.1.4 on 2026-03-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book'),
        ('api', '0003_remove_user_email'),
    ]

    operations = [
    ]
