# Generated by Django 4.2.29 on 2026-03-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_book"),
        ("api", "0003_remove_user_email"),
    ]

    operations = []
