# Generated by Django 4.2.29 on 2026-03-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="copies_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
