# Generated by Django 5.2.11 on 2026-03-24 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_wishlistitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "book")},
        ),
    ]
